version: 2.1

jobs:
  yamllint:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: |
            pip install yamllint
      - run:
          name: Run yamllint
          command: |
            yamllint **/*.yml

  terraform-validate:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Run terraform validate
          command: |
            terraform init
            terraform validate

  tflint:
    docker:
      - image: chinmaigowda/terraform-tflint:latest1  # Use your custom image
    steps:
      - checkout
      - run:
          name: Run TFLint
          command: |
            tflint **/*.tf

  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Define workflows
workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - yamllint
      - terraform-validate
      - tflint
      - say-hello
