version: 2.1

jobs:
  yamllint:
    docker:
      - image: cimg/python:3.9  # Use a CircleCI Python image
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: |
            pip install yamllint
      - run:
          name: Run yamllint
          command: |
            yamllint **/*.yml

  terraform-validate:
    docker:
      - image: hashicorp/terraform:latest  # Use HashiCorp's Terraform Docker image
    steps:
      - checkout
      - run:
          name: Run terraform validate
          command: |
            terraform init
            terraform validate

  # Job to lint Terraform files using TFLint
  tflint:
    docker:
      - image: stagex/tflint:latest  # Use stagex/tflint image
    steps:
      - checkout
      - run:
          name: Run TFLint
          command: |
            /usr/local/bin/tflint **/*.tf  # Run TFLint directly with its full path

  # Job to say hello
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Define workflows
workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - yamllint
      - terraform-validate
      - tflint
      - say-hello
